FROM registry.redhat.io/codeready-workspaces/plugin-java11-rhel8@sha256:cff9e47f83c6140d442721ed4d78e029a55f98bdca8efffbba8513656a1b28a7

USER root

ENV ANSIBLE_VERSION="2.9.27"

RUN INSTALL_PKGS="python36 python36-devel python3-virtualenv python3-setuptools python3-pip \
        nss_wrapper httpd httpd-devel mod_ssl mod_auth_gssapi \
        mod_ldap mod_session atlas-devel gcc-gfortran libffi-devel \
        libtool-ltdl enchant" && \
    yum -y module enable python36:3.6 httpd:2.4 && \
    yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    # Remove redhat-logos-httpd (httpd dependency) to keep image size smaller.
    rpm -e --nodeps redhat-logos-httpd && \
    yum -y clean all --enablerepo='*'

RUN python3.6 -m pip install --upgrade pip && \
    python3.6 -m pip install --no-cache-dir virtualenv && \
    python3.6 -m pip install --upgrade setuptools


RUN pip install "ansible==${ANSIBLE_VERSION}" \
    ansible-lint

USER jboss
ENTRYPOINT ["/home/jboss/entrypoint.sh"]
WORKDIR /projects
